services:
  bestbuy:
    image: ghcr.io/subasically/bestbuy-bot:latest
    container_name: bestbuy_bot
    restart: always
    environment:
      BESTBUY_URL: "https://www.bestbuy.com/site/lg-ultragear-45-oled-curved-wqhd-240hz-0-03ms-freesync-and-nvidia-g-sync-compatible-gaming-monitor-with-hdr10-black/6530356.p?skuId=6530356"
      EMAIL_FROM: "alensubasic@gmail.com"
      EMAIL_TO: "alensubasic@gmail.com"
      SMTP_SERVER: "smtp.gmail.com"
      SMTP_PORT: "587"
      EMAIL_PASSWORD: "vstr lket esxl owvb"
      DISPLAY: ":99"